[package]
name = "glium-shader-template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.18.1"
lazy_static = "1.4.0"
svg2pts = "0.1.5"
num = "0.4.0"