[package]
name = "glium-shader-template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
svg2pts = { path = "./lib/svg2pts" }
nannou = "0.18.1"
lazy_static = "1.4.0"
num = "0.4.0"